# PCA

In [4]:
from sklearn.datasets import load_iris

# Load the Iris dataset
iris_dataset = load_iris()

# Access the features and target variable
X = iris_dataset.data  # Features (data matrix)
y = iris_dataset.target  # Classification target

In [15]:
import numpy as np
mean_values = np.mean(X, axis=0)
variance_values = np.var(X, axis=0)
std_X = (X - mean_values)/variance_values
print(std_X)

[[-1.09133619e+00  2.34571507e+00 -7.61750273e-01 -1.73154806e+00]
 [-1.38496925e+00 -3.03812494e-01 -7.61750273e-01 -1.73154806e+00]
 [-1.67860231e+00  7.55998530e-01 -7.94055204e-01 -1.73154806e+00]
 [-1.82541883e+00  2.26093018e-01 -7.29445342e-01 -1.73154806e+00]
 [-1.23815272e+00  2.87562058e+00 -7.61750273e-01 -1.73154806e+00]
 [-6.50886609e-01  4.46533711e+00 -6.64835480e-01 -1.38500742e+00]
 [-1.82541883e+00  1.81580955e+00 -7.61750273e-01 -1.55827774e+00]
 [-1.23815272e+00  1.81580955e+00 -7.29445342e-01 -1.73154806e+00]
 [-2.11905189e+00 -8.33718005e-01 -7.61750273e-01 -1.73154806e+00]
 [-1.38496925e+00  2.26093018e-01 -7.29445342e-01 -1.90481838e+00]
 [-6.50886609e-01  3.40552609e+00 -7.29445342e-01 -1.73154806e+00]
 [-1.53178578e+00  1.81580955e+00 -6.97140411e-01 -1.73154806e+00]
 [-1.53178578e+00 -3.03812494e-01 -7.61750273e-01 -1.90481838e+00]
 [-2.26586842e+00 -3.03812494e-01 -8.58665065e-01 -1.90481838e+00]
 [-6.36204956e-02  4.99524263e+00 -8.26360135e-01 -1.73154806e

In [21]:
cov = np.cov(std_X.T)
print(cov.shape)
print(cov)

(4, 4)
[[ 1.47801874 -0.33013183  0.60439479  1.31333827]
 [-0.33013183  5.33461925 -0.56432428 -1.11685499]
 [ 0.60439479 -0.56432428  0.32521743  0.72521551]
 [ 1.31333827 -1.11685499  0.72521551  1.74433207]]


In [22]:
eig_vals = np.linalg.eig(cov)
print(eig_vals)

(array([5.90436257, 2.73033279, 0.2380396 , 0.00945254]), array([[-0.18745664,  0.64787489,  0.72258444,  0.1516241 ],
       [ 0.91163197,  0.39444472, -0.1093713 , -0.03712713],
       [-0.15554956,  0.25152848, -0.06590395, -0.95299235],
       [-0.33104605,  0.60116963, -0.67938672,  0.25968689]]))
